//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.30 at 11:38:41 AM CET 
//


package pojo;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the pojo package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {




    /**
     * Create an instance of {@link PreservationConfiguration.ClassiDocumentali.ClasseDocumentale }
     * 
     */
    public PreservationConfiguration.ClassiDocumentali.ClasseDocumentale createPreservationConfigurationClassiDocumentaliClasseDocumentale() {
        return new PreservationConfiguration.ClassiDocumentali.ClasseDocumentale();
    }

    /**
     * Create an instance of {@link PreservationConfiguration.ClassiDocumentali.ClasseDocumentale.Mappings.MetadataSystem }
     * 
     */
    public PreservationConfiguration.ClassiDocumentali.ClasseDocumentale.Mappings.MetadataSystem createPreservationConfigurationClassiDocumentaliClasseDocumentaleMappingsMetadataSystem() {
        return new PreservationConfiguration.ClassiDocumentali.ClasseDocumentale.Mappings.MetadataSystem();
    }

    /**
     * Create an instance of {@link PreservationConfiguration.ClassiDocumentali.ClasseDocumentale.Mappings }
     * 
     */
    public PreservationConfiguration.ClassiDocumentali.ClasseDocumentale.Mappings createPreservationConfigurationClassiDocumentaliClasseDocumentaleMappings() {
        return new PreservationConfiguration.ClassiDocumentali.ClasseDocumentale.Mappings();
    }

    /**
     * Create an instance of {@link PreservationConfiguration.ClassiDocumentali.ClasseDocumentale.Mappings.MetadataSystem.Allegati.Key }
     * 
     */
    public PreservationConfiguration.ClassiDocumentali.ClasseDocumentale.Mappings.MetadataSystem.Allegati.Key createPreservationConfigurationClassiDocumentaliClasseDocumentaleMappingsMetadataSystemAllegatiKey() {
        return new PreservationConfiguration.ClassiDocumentali.ClasseDocumentale.Mappings.MetadataSystem.Allegati.Key();
    }

    /**
     * Create an instance of {@link PreservationConfiguration.ClassiDocumentali.ClasseDocumentale.Mappings.MetadataCustom }
     * 
     */
    public PreservationConfiguration.ClassiDocumentali.ClasseDocumentale.Mappings.MetadataCustom createPreservationConfigurationClassiDocumentaliClasseDocumentaleMappingsMetadataCustom() {
        return new PreservationConfiguration.ClassiDocumentali.ClasseDocumentale.Mappings.MetadataCustom();
    }

    /**
     * Create an instance of {@link PreservationConfiguration.ClassiDocumentali.ClasseDocumentale.Mappings.MetadataCustom.Allegati }
     * 
     */
    public PreservationConfiguration.ClassiDocumentali.ClasseDocumentale.Mappings.MetadataCustom.Allegati createPreservationConfigurationClassiDocumentaliClasseDocumentaleMappingsMetadataCustomAllegati() {
        return new PreservationConfiguration.ClassiDocumentali.ClasseDocumentale.Mappings.MetadataCustom.Allegati();
    }

    /**
     * Create an instance of {@link PreservationConfiguration.ClassiDocumentali }
     * 
     */
    public PreservationConfiguration.ClassiDocumentali createPreservationConfigurationClassiDocumentali() {
        return new PreservationConfiguration.ClassiDocumentali();
    }

    /**
     * Create an instance of {@link PreservationConfiguration.ClassiDocumentali.ClasseDocumentale.Mappings.MetadataSystem.Allegati }
     * 
     */
    public PreservationConfiguration.ClassiDocumentali.ClasseDocumentale.Mappings.MetadataSystem.Allegati createPreservationConfigurationClassiDocumentaliClasseDocumentaleMappingsMetadataSystemAllegati() {
        return new PreservationConfiguration.ClassiDocumentali.ClasseDocumentale.Mappings.MetadataSystem.Allegati();
    }

    /**
     * Create an instance of {@link PreservationConfiguration.ClassiDocumentali.ClasseDocumentale.Mappings.MetadataCustom.Allegati.Key }
     * 
     */
    public PreservationConfiguration.ClassiDocumentali.ClasseDocumentale.Mappings.MetadataCustom.Allegati.Key createPreservationConfigurationClassiDocumentaliClasseDocumentaleMappingsMetadataCustomAllegatiKey() {
        return new PreservationConfiguration.ClassiDocumentali.ClasseDocumentale.Mappings.MetadataCustom.Allegati.Key();
    }

    /**
     * Create an instance of {@link PreservationConfiguration }
     * 
     */
    public PreservationConfiguration createPreservationConfiguration() {
        return new PreservationConfiguration();
    }

    /**
     * Create an instance of {@link PreservationConfiguration.ClassiDocumentali.ClasseDocumentale.Mappings.MetadataSystem.DocPrincipale.Key }
     * 
     */
    public PreservationConfiguration.ClassiDocumentali.ClasseDocumentale.Mappings.MetadataSystem.DocPrincipale.Key createPreservationConfigurationClassiDocumentaliClasseDocumentaleMappingsMetadataSystemDocPrincipaleKey() {
        return new PreservationConfiguration.ClassiDocumentali.ClasseDocumentale.Mappings.MetadataSystem.DocPrincipale.Key();
    }

    /**
     * Create an instance of {@link PreservationConfiguration.ClassiDocumentali.ClasseDocumentale.Mappings.MetadataCustom.DocPrincipale.Key }
     * 
     */
    public PreservationConfiguration.ClassiDocumentali.ClasseDocumentale.Mappings.MetadataCustom.DocPrincipale.Key createPreservationConfigurationClassiDocumentaliClasseDocumentaleMappingsMetadataCustomDocPrincipaleKey() {
        return new PreservationConfiguration.ClassiDocumentali.ClasseDocumentale.Mappings.MetadataCustom.DocPrincipale.Key();
    }

    /**
     * Create an instance of {@link PreservationConfiguration.ClassiDocumentali.ClasseDocumentale.Mappings.MetadataSystem.DocPrincipale }
     * 
     */
    public PreservationConfiguration.ClassiDocumentali.ClasseDocumentale.Mappings.MetadataSystem.DocPrincipale createPreservationConfigurationClassiDocumentaliClasseDocumentaleMappingsMetadataSystemDocPrincipale() {
        return new PreservationConfiguration.ClassiDocumentali.ClasseDocumentale.Mappings.MetadataSystem.DocPrincipale();
    }

    /**
     * Create an instance of {@link PreservationConfiguration.ClassiDocumentali.ClasseDocumentale.Mappings.MetadataCustom.DocPrincipale }
     * 
     */
    public PreservationConfiguration.ClassiDocumentali.ClasseDocumentale.Mappings.MetadataCustom.DocPrincipale createPreservationConfigurationClassiDocumentaliClasseDocumentaleMappingsMetadataCustomDocPrincipale() {
        return new PreservationConfiguration.ClassiDocumentali.ClasseDocumentale.Mappings.MetadataCustom.DocPrincipale();
    }

}
